<?php

namespace WebImage\Blocks\Templates\Plugins;

use WebImage\Blocks\Templates\Parsers\Branch;
use WebImage\Blocks\Templates\Parsers\BranchArgumentDefinition;
use WebImage\Blocks\Templates\Parsers\ParserException;
use WebImage\Blocks\Templates\Parsers\ParserState;
use WebImage\Blocks\Templates\Parsers\Plugins\AbstractMacroParser;
use WebImage\Blocks\Templates\Parsers\TemplateParser;
use WebImage\Blocks\Templates\Parsers\VariableTypes;
use WebImage\Blocks\Templates\Transpilers\Plugins\TranspilerPluginTrait;
use WebImage\Blocks\Templates\Transpilers\TranspilerPluginInterface;
use WebImage\Blocks\Templates\Transpilers\TranspilerState;

class PropertyMacro extends AbstractMacroParser implements TranspilerPluginInterface
{
    use TranspilerPluginTrait;
    const MACRO_PROPERTY = 'property';
//    const META_BLOCK_PROPERTIES = 'block.properties';
    const META_PROPERTIES = 'properties';

    protected array $supportedMacros = [self::MACRO_PROPERTY];

    public static function getArgumentDefinitions(string $macroName): array
    {
        return [
            new BranchArgumentDefinition('name', 'The name of a block property.', true),
            new BranchArgumentDefinition('type', 'The property type, e.g. int, string, float.', true),
            new BranchArgumentDefinition('default', 'The default value for the property.')
        ];
    }

    protected function processArguments(ParserState $state, array $args)
    {
        $name = self::getArgumentStringByName($this->getMacroName(), $args, 'name');
        $type = self::getArgumentStringByName($this->getMacroName(), $args, 'type');
        $default = self::getArgumentValueByName($this->getMacroName(), $args, 'default');

        $metaProperties = $state->meta[self::META_PROPERTIES] ?? [];

        if (isset($metaProperties[$name])) {
            throw new ParserException('Only one property can be defined for ' . $name);
        }

        $metaProperties[$name] = [
            'type' => VariableTypes::validType($type),
            'default' => $default
        ];

        $state->meta[self::META_PROPERTIES] = $metaProperties;
    }

	protected function getMeta(): array
	{

		return parent::getMeta(); // TODO: Change the autogenerated stub
	}


	private function getValidTypes(): array
    {
        return [
            self::TYPE_INT,
            self::TYPE_STRING,
            self::TYPE_FLOAT
        ];
    }

    public function canTranspile(TranspilerState $state, Branch $branch): bool
    {
        return $branch->getType() == TemplateParser::T_MACRO && $branch->getValue() == self::MACRO_PROPERTY;
    }

    public function transpile(TranspilerState $state, Branch $branch): string
    {
        return '';
    }
}
